#!/usr/bin/env bash
# Pack Nosey Little Bird.
#   staff — shared team build (distribute this)
#   dev   — personal-only extras (Bird Brain, etc.); do not share with staff
# Usage: scripts/pack-extension.sh staff|dev
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROFILE="${1:-}"
if [[ "$PROFILE" != "staff" && "$PROFILE" != "dev" ]]; then
  echo "Usage: $0 staff|dev" >&2
  exit 1
fi

OUT_STAFF="${NOSY_STAFF_OUT:-/home/chaos/Documents/nosey-little-bird-staff}"
OUT_DEV="${NOSY_DEV_OUT:-/home/chaos/Documents/nosey-little-bird-dev}"
if [[ "$PROFILE" == "staff" ]]; then
  OUT="$OUT_STAFF"
else
  OUT="$OUT_DEV"
fi

TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

# Stage tree
rsync -a --delete \
  --exclude '.git' \
  --exclude '.worktrees' \
  --exclude 'node_modules' \
  --exclude 'docs' \
  --exclude 'dist' \
  --exclude 'scripts/pack-extension.sh' \
  "$ROOT/" "$TMP/"

# Stamp profile (ESM for SW/popup + classic inject for HubSpot content script)
cat > "$TMP/build-profile.js" <<EOF
/**
 * Build profile — generated by scripts/pack-extension.sh ($PROFILE)
 * Do not edit by hand in packed trees; change workspace then re-pack.
 */
export const BUILD_PROFILE = "$PROFILE";

export const IS_DEV = BUILD_PROFILE === "dev";
export const IS_STAFF = BUILD_PROFILE === "staff";

export const FEATURES = {
  birdBrain: IS_DEV,
  birdBrainImportExport: IS_DEV,
  customAlertSound: IS_DEV,
  historyPage: IS_DEV,
  historyMaxEntries: IS_DEV ? 2000 : 0,
  hudRefreshMs: IS_DEV ? 3000 : 8000,
  showBuildBadge: true,
};

export function buildLabel() {
  return IS_DEV ? "DEV" : "STAFF";
}
EOF

if [[ "$PROFILE" == "dev" ]]; then
  cat > "$TMP/content-features.js" <<'EOF'
/** Classic inject for content.js — generated (dev). */
globalThis.__BIRD_FEATURES__ = {
  birdBrain: true,
  birdBrainImportExport: true,
  customAlertSound: true,
  historyPage: true,
  historyMaxEntries: 2000,
  hudRefreshMs: 3000,
  showBuildBadge: true,
  buildLabel: "DEV",
};
EOF
else
  cat > "$TMP/content-features.js" <<'EOF'
/** Classic inject for content.js — generated (staff). */
globalThis.__BIRD_FEATURES__ = {
  birdBrain: false,
  birdBrainImportExport: false,
  customAlertSound: false,
  historyPage: false,
  historyMaxEntries: 0,
  hudRefreshMs: 8000,
  showBuildBadge: true,
  buildLabel: "STAFF",
};
EOF
fi

# Staff: drop heavy / unused history UI assets
if [[ "$PROFILE" == "staff" ]]; then
  rm -f "$TMP/history.html" "$TMP/history.js"
fi

# Name in manifest
python3 - <<PY
import json
from pathlib import Path
p = Path("$TMP/manifest.json")
m = json.loads(p.read_text())
ver = m.get("version", "0")
if "$PROFILE" == "staff":
    m["name"] = "Nosey Little Bird"
    m["short_name"] = "Nosey Bird"
    m["description"] = "Strobe queue alerts, HubSpot order lookup, and who's on shift — staff build."
    # Drop history from WAR if present
    for block in m.get("web_accessible_resources", []):
        block["resources"] = [r for r in block.get("resources", []) if "history" not in r]
else:
    m["name"] = "Nosey Little Bird! Who Dat? Edition (DEV)"
    m["short_name"] = "Who Dat? DEV"
    m["description"] = "Dev build: staff features plus Bird Brain history."
p.write_text(json.dumps(m, indent=2) + "\n")
print(f"packed {ver} profile=$PROFILE -> $OUT")
PY

mkdir -p "$(dirname "$OUT")"
rsync -a --delete "$TMP/" "$OUT/"
echo "Done: $OUT"

# Brave load-unpacked path on Black (staff bird) — keep in sync so releases aren't "GitHub only"
LIVE_STAFF="${NOSY_LIVE_STAFF:-/home/chaos/Documents/nosey-little-bird-v2.0.0}"
if [[ "$PROFILE" == "staff" && -d "$LIVE_STAFF" ]]; then
  rsync -a --delete "$OUT/" "$LIVE_STAFF/"
  echo "Synced live Brave folder: $LIVE_STAFF"
fi
